### ISSUE TITLE
A question about the evolution of this repository

### ISSUE THREAD

**Issue by tao-ji** [square/tape#185]
Hi,

I find this repository has some initial commits from your another repository square/retrofit.
![image](https://user-images.githubusercontent.com/19903046/34505251-dfb9125c-efd8-11e7-8d6b-94db57a22e42.png)
These commits have different sha in git graph. I thought that you have cherry-picked some commits from retrofit, but they have the same committed date. As far as I know, the cherry-picked commits should have the different committed dates. Would you please tell me that how you pick other commits and keep the committed dates unchanged?

Best,
Tao Ji

**Comment by JakeWharton** [comment]
Retrofit used to be a dumping ground of a bunch of code. One of my first projects at Square was separating them into distinct repos. This was done by filtering the history to retain only commits that affected each project. As a result there are duplicate commits but due to the filtering they have different SHAs since the commit contains only the changes relevant to each project.
