### ISSUE TITLE
Clarification on transactionality

### ISSUE THREAD

**Issue by epsstan** [square/tape#81]
I generally understand how transactionality is preserved, by writing ("comitting") the header after writing data. However, I'm not clear on how it's implemented and the disclaimer about atomic segment writes.

According to @crazybob (https://www.parleys.com/tutorial/5148922b0364bc17fc56c97b/chapter15) there are 2 fsyncs : 
1) write data
2) fsync
3) write header
4) fsync

But I don't see any explicit call to sync. Is this because opening the file in "rwd" is equivalent to an explicit sync ? According to the RandomAccessFile javadocs, "rwd" mode is 

" If the file resides on a local storage device then when an invocation of a method of this class returns it is guaranteed that all changes made to the file by that invocation will have been written to that device. "

If that is the case what is the need for this disclaimer ?

"The current implementation is built for file systems that support atomic segment writes (like YAFFS)."

Or is it the case that even with "rwd", the write is not atomic, in which case the javadoc is wrong ??

Feels like I'm missing something. Thanks.

**Comment by f2prateek** [comment]
`fsync` (or opening it in `rwd` mode) doesn't guarantee atomicity, it only guarantees that the data has been written to the file when it returns.

Consider the case when you write a 1MB of data into a file and call `fsync`, the file system will typically break it down into chunks and writes it to the file one chunk at a time. If an exceptional failure (such as a power failure, process death or system crashes) happens during this, some chunks may have not been written yet.

However, if the file system guarantees atomic segment writes, it assures that as long as you write data smaller than the size of a segment, it's all or nothing operation, even during exceptional failures.

By designing the header to be smaller than the size of a segment, QueueFile can ensure that writing the header (which is much smaller than the size of a segment) is atomic. Even during exceptional failures, the mutating change will simply be aborted since the header isn't updated. If the file system doesn't guarantee atomic segment writes, then the header may be written only partially and leave the QueueFile in an invalid state.

**Comment by epsstan** [comment]
Makes sense. Thanks for clarifying.
