### ISSUE TITLE
[Question] Synchronous writes and performance considerations

### ISSUE THREAD

**Issue by mttkay** [square/tape#84]
The docs of `QueueFile` mention that "writes are synchronous". Since Tape advertises itself as being lightning fast, I wonder how fast this really is compared to, say, a relational database such as SQLite? Performing disk I/O with every insert doesn't exactly sound fast to me, and it's the reason why for instance SQLite use [page caches](https://www.sqlite.org/fileio.html#tocentry_139) and Android's `SharedPreferences` introduced `apply` for eventual consistency with the underlying file system.

Have there been measurements made around how fast Tape really is compared to any of the mentioned persistence options? Any concerns around event/task frequency when appending to the log?

We are evaluating Tape as a simple persistence layer for tracking events. The API lends itself very well to the kind of interaction we're aiming for, but I'm concerned about performance since we will perform multiple writes per second e.g. when audio is playing. This wasn't a problem with SQLite for above mentioned reasons. Would you advise to manually buffer these events in memory first, then flush them to disk every now and then?

**Comment by JakeWharton** [comment]
Shared preferences are not durable. A power loss after a write is not
guaranteed to have made it to disk. I'm not sure it guarantees consistency
in such an event either, but I haven't looked at it's implementation. Since
a global lock is used, they are atomic, but at a high cost.

SQLite is full ACID. Writes are both atomic and durable. This means that
before a transaction (or one-off) statement can return, it must be written
to disk. This usually involves an append-only transaction log which is
periodically "flushed" into the main file but it requires an fsync or
durability guarantees on the filesystem.

Tape is append-only so at worst it's as performant as SQLite's transaction
log only (if you include the actual DB file and the "flush"ing SQLite will
be massively slower in comparison). We don't really need to measure speed
because of the format simplicity. Writes stream to the filesystem as fast
as you can send and it allows and then an atomic change it made to the
header which amounts to a single filesystem segment write. Since we require
single-threaded interaction we don't have to worry about concurrency like a
SQLite would.
